### PR TITLE
Added support for unicorns

### PR DESCRIPTION
**Pull request by pietdaniel**
This PR allows for `sl` to have a static unicorn move across the screen.

### CODE REVIEW

**Comment by danog** [comment]
This sounds nice, but the Unicorn option spits out a segfault.

**Comment by pietdaniel** [comment]
ouch, works on my machine, what are you running so I can try and debug against different targets.

**Comment by danog** [comment]
I am running a 14.04 amd64 ubuntu server (xeon).

Il mercoledì 21 ottobre 2015, pietdaniel <notifications@github.com> ha
scritto:

> ouch, works on my machine, what are you running so I can try and debug
> against different targets.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mtoyoda/sl/pull/31#issuecomment-150003742>.
>


-- 
*Website: http://daniil.it <http://dano.cu.cc/1A0pUZV>*

**Comment by mtoyoda** [comment]
Wow. Great, but why unicorns?
Anyway I'd like to keep sl as simple as possible.

**Pull request closed without merging**
