### PR TITLE
Add -e option: Interrupt via Ctrl+C, Proper Makefile, and Cleanup sl.h

### PR DESCRIPTION
**Pull request by ryanmjacobs**
Add -e option to allow interrupt via Ctrl+C. So users can, `alias sl='sl -e'` if they don't want to wait each time for sl to finish running.
- Makefile now includes: install, uninstall, and clean. Therefore, users can install sl by running:

```
make
make install
```
- Add header guards to `sl.h`, and move function prototypes to `sl.h`.
- `README.ja.md` and `sl.1.ja` still need to be updated (I don't know Japanese).

### CODE REVIEW

**Comment by Jonathan50** [comment]
I get impatient because I mistype `ls` as `sl` very often :stuck_out_tongue:

**Comment by Jonathan50** [comment]
Hm. I applied this patch and the manpage has changed and the source does say it's changed but `-e` doesn't work...

**Comment by ryanmjacobs** [comment]
@Jonathan50 Sorry for the late reply. My inbox has been stuffed lately.

Can you please try these commands in order?
```bash
$  git clone https://github.com/ryanmjacobs/sl
$ cd sl
$ make
$ ./sl -e
```

**Comment by Jonathan50** [comment]
It works. But if I modify the PKGBUILD to apply the patch it doesn't work.

**Comment by ryanmjacobs** [comment]
Can you try this one? https://gist.github.com/ryanmjacobs/a97a564e1085487ad553

(I basically took [sl-git](https://aur.archlinux.org/packages/sl-git/), and switched out `mtoyoda` with `ryanmjacobs`)

**Comment by Jonathan50** [comment]
Works great thanks

**Pull request closed without merging**
