### PR TITLE
Add a fabulous rainbow option

### PR DESCRIPTION
**Pull request by KoffeinFlummi**
2015-04-28-085739_1097x640_scrot

### CODE REVIEW

**Comment by danog** [comment]
Niiiiiice! :)

**Comment by bunnyswe** [comment]
awesome

**Comment by terratronix** [comment]
This sums up what coding is all about

**Comment by GeekLogan** [comment]
+1 for creativity

**Comment by mtoyoda** [comment]
Great! Thanks for your nice patch, but I'd like to keep sl as simple as possible.

**Comment by PartialVolume** [comment]
Definitely like the rainbow option.

**Pull request closed without merging**
