### PR TITLE
Add an option -d , that make people dance on top if it is not going to accident.

### PR DESCRIPTION
**Pull request by Suloch**
Adding dancers to the locomotive top. Inspired by song "chaiya-chaiya(Shahrukh Khan)".

### CODE REVIEW

**Comment by LegoStormtroopr** [comment]
Would you mind taking a screen captureof the dancers for those of us without much C knowledge?

**Comment by ryanmjacobs** [comment]
Bam! Here you go:
sl-d

**Comment by LegoStormtroopr** [comment]
:+1: I cannot stress how important this is!

:dancers::dancers::dancers::dancers::dancers::dancers::dancers:

**Comment by mtoyoda** [comment]
Great! But I'd like to keep sl as simple as possible.

**Pull request closed without merging**
