### PR TITLE
feat: Add file cars

### LINKED ISSUE #57: This broke ls...
I will never be able to (properly) use `ls` again. Just want to see the little train go. Choo-choo!

Sometimes I misspell `sl`, and the list of dirs/files appears, which could even be useful, but.... I'm now considering to symlink `ls` to this, so I will not miss the little train.

Choo-coo!

### PR DESCRIPTION
**Pull request by scaryrawr**
Ok... Maybe the point of the tool was to just be silly, but I thought it would be funny if it still showed the directory contents (somehow), so I added train cars and it waits until the last train car makes it across the screen. Doesn't show dotfiles.

- Also add cmake
- Add vscode settings for cmake

Fixes #57

### CODE REVIEW

**Comment by ACBob** [comment]
I would've made this an issue on your fork, but i can't seem to...
But when this version of sl is used in a large directory (I.e `/bin`, or in my case, my home directory) it will chug along happily.. for a while, until it segfaults.

**Comment by ACBob** [comment]
A few other things i'd noticed were;
`-F` will take all the cars up, and if your directory is too big, you'll be staring at a blank screen for a while.
`-l` will have no file cars at all.

**Comment by scaryrawr** [comment]
> A few other things i'd noticed were;
> `-F` will take all the cars up, and if your directory is too big, you'll be staring at a blank screen for a while.
> `-l` will have no file cars at all.

I've enabled issues on my fork.

**Comment by ACBob** [comment]
I'll transfer my comments to issues accordingly.

**Pull request closed without merging**
